export const SHOW_HISTORY = 'SHOW_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const SELECT_HISTORY_ITEM = 'SELECT_HISTORY_ITEM';
export const PRESS_EQUALS = 'PRESS_EQUALS';
export const PRESS_CLEAR = 'PRESS_CLEAR';
export const PRESS_DIGIT = 'PRESS_DIGIT';
export const PRESS_DECIMAL = 'PRESS_DECIMAL';
export const PRESS_OPERATION = 'PRESS_OPERATION';