export const MAX_DIGITS = 16;

export const calculatorButtons = [
    {
        id:"clear",
        type:"clear-all",
        text:"AC"
    },
    {
        id:"divide",
        type:"operation",
        text:"/"
    },
    {
        id:"multiply",
        type:"operation",
        text:"*"
    },
    {
        id:"seven",
        type:"number",
        text:"7"
    },
    {
        id:"eight",
        type:"number",
        text:"8"
    },
    {
        id:"nine",
        type:"number",
        text:"9"
    },
    {
        id:"four",
        type:"number",
        text:"4"
    },
    {
        id:"five",
        type:"number",
        text:"5"
    },
    {
        id:"six",
        type:"number",
        text:"6"
    },
    {
        id:"one",
        type:"number",
        text:"1"
    },
    {
        id:"two",
        type:"number",
        text:"2"
    },
    {
        id:"three",
        type:"number",
        text:"3"
    },
    {
        id:"zero",
        type:"number",
        text:"0"
    },
    {
        id:"subtract",
        type:"operation",
        text:"-"
    },
    {
        id:"decimal",
        type:"decimal",
        text:"."
    },
    {
        id:"add",
        type:"operation",
        text:"+"
    },
    {
        id:"equals",
        type:"operation equals",
        text:"="
    },
];